spring.config.import=optional:file:.env[.properties]
spring.application.name=internet-shop


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.parameters.validCheckSum=ANY

jwt.secret=${JWT_SECRET}
jwt.access_token.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh_token.expiration=${JWT_REFRESH_EXPIRATION}
jwt.reset_token.expiration=${JWT_RESET_EXPIRATION}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.reset-password-url=${RESET_PASSWORD_URL}
admin.email=${ADMIN_EMAIL}

server.servlet.session.timeout=86400
